# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json* ./
RUN npm install --ignore-scripts --no-audit --production=false

# Copy source code
COPY . .

# Build TypeScript using esbuild (fast bundler)
RUN npm run build

# Remove dev dependencies
RUN npm prune --production

# Launch the MCP server using stdio
CMD ["node", "dist/index.js"]
