#!/usr/bin/env python3
"""dream-ranker: rank Todoist tasks against weekly/monthly/annual goals.

Stub generated by Dream v2 (2026.05.23). Logic ported from
~/vault/i447/i446/dream-runs/2026.05.23-dry-run/logs/scoring.json generator.
"""
from __future__ import annotations
import json, re, sys
from datetime import date, datetime
from pathlib import Path

WEEKLY_TERMS = {
    "i9": ["i9","xbox","hr","process","response","question","ask","offsite",
           "analytics","roadmap","jay","andy","ben","joe","coreai","microsoft",
           "slack github","teams","ibx i9"],
    "m5x2": ["m5x2","janowski","march question","roadmap","ai dashboard","matt",
             "fund","lp","investor","p&l","budget","real estate","ian","carolina",
             "profit distribution","inflation","returns"],
}
ANNUAL_TERMS = ["microsoft","growth","fund","fund iv","fund iii","real estate",
                "net worth","kids","family","health","learning"]


def due_score(d: str | None, today: date) -> int:
    if not d: return 0
    try: delta = (datetime.fromisoformat(d[:10]).date() - today).days
    except Exception: return 0
    if delta < 0 or delta <= 1: return 3
    if delta <= 7: return 2
    if delta <= 30: return 1
    return 0


def dream_doability(c: str) -> int:
    lo = c.lower()
    if any(x in lo for x in ["buy","book","purchase","send out","send all",
                              "schedule","submit","payment"]): return 1
    if any(x in lo for x in ["draft","write","review","read","research","list",
                              "checklist","plan","questions","roadmap","prep",
                              "claude","automated","implement"]): return 5
    if any(x in lo for x in ["followup","follow up","respond","ask","contact",
                              "reach out"]): return 4
    return 2


def risk(c: str) -> str:
    lo = c.lower()
    if any(x in lo for x in ["buy","purchase","book","payment","hire"]):
        return "forbidden"
    if any(x in lo for x in ["send","respond","followup","follow up","ask",
                              "contact","reach out","email","slack","teams"]):
        return "approval-required"
    return "none"


def artifact(c: str, r: str) -> str:
    lo = c.lower()
    if r == "approval-required": return "approval card"
    if r == "forbidden": return "blocked"
    if any(x in lo for x in ["implement","automated","cron","formula"]): return "branch"
    if any(x in lo for x in ["read","research","review"]): return "research memo"
    if any(x in lo for x in ["list","checklist","plan","prep","questions","roadmap"]): return "checklist"
    return "draft"


def score(task: dict, today: date) -> dict:
    c = task["content"]
    lo = c.lower()
    labels = [x.lower() for x in task.get("labels", [])]
    wm = 0
    for domain, terms in WEEKLY_TERMS.items():
        if domain in labels: wm = max(wm, 3)
        if any(term in lo for term in terms):
            wm = max(wm, 5 if domain in labels else 4)
    mm = 2 if ("m5x2" in labels or "i9" in labels) else 0
    am = 2 if any(term in lo for term in ANNUAL_TERMS) else 0
    ds = due_score(task.get("due"), today)
    dd = dream_doability(c)
    r = risk(c)
    mins = task.get("mins"); fen = task.get("fen")
    fpm = (fen / mins) if (fen and mins) else None
    total = wm*10 + mm*4 + am*3 + ds*3 + dd*5 + (fpm or 0)
    return {**task, "weekly_goal_match": wm, "monthly_goal_match": mm,
            "annual_goal_match": am, "due_urgency": ds, "fen_per_minute": fpm,
            "dream_doability": dd, "external_action_risk": r,
            "expected_artifact": artifact(c, r), "score": round(total, 2)}


def main():
    src = json.loads(Path(sys.argv[1]).read_text()) if len(sys.argv) > 1 else json.load(sys.stdin)
    today = date.today()
    tasks = src.get("tasks", src) if isinstance(src, dict) else src
    ranked = sorted((score(t, today) for t in tasks), key=lambda x: x["score"], reverse=True)
    print(json.dumps({"generated_at": datetime.now().isoformat(),
                      "authority": "weekly > monthly > annual > todoist > calendar",
                      "top": ranked[:40]}, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
